# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import emoji as em





class Ui_MainWindow(object):
    def on_donebtn_clicked(self):
        input_emoji = self.einput.text()


        if not(em.is_emoji(input_emoji)):
            error_message = (
                "<html><body>"
                "<p style='color: red; font-size: 16px;'>"
                "Error: Please input an emoji. "
                "<p  style='color: red; font-size: 16px;'>You can get help with this website <a href='https://www.webfx.com/tools/emoji-cheat-sheet/'>CLICK RIGHT AND COPY THE LINK</a>.</p>"
                "</p>"
                "</body></html>"
            )
            self.error.setHtml(error_message)
            self.error.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        else:
            self.error.setHtml("")
            em_ls=["😫","😰","😓","😢","😩","😥","😖","😨","😞","😦","😭","😣","😵","😑","😧","😔","😕","😳","😬","😱","🥺","😒","😩","😟","😯","😐","😲","🙁","😮","😧","😦","😕","😟","😶","😰","😑","😞","😦","😔","😳","😨","😓","😕","😢","😵","😧","😩","😲","😫","😩","😯","😑","😩","😥","😓","😦","😢","😞","😖","😨","😰","😧","😔","😵","😑","😩","😟","😦","😳","😓","😰","😨","😞","😖","😧","😕","😭","😩","😔","😱","😮","😦","😯","😑","😧","😳","😵","😩","😞","😖","😰","😧","😓","😥","😲","😩","😟","😔","😶","😑"]

            if input_emoji in em_ls:
                for i in range(0,99):
                    if em_ls[i] == input_emoji:
                        self.elvl.setValue(100-i)
                        break
            
                
            else:
                self.elvl.setValue(0)
            ch=em.demojize(input_emoji , language='fr')
            ch=ch.replace("_", " ")
            self.edesc.setStyleSheet("font-weight: bold;"
                                     "background-color:white;"
                                     "font-size:18pt"
                                     )
            self.edesc.setPlainText(input_emoji + ch[1:len(ch)-1])



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1095, 524)
        MainWindow.setStyleSheet("background-color: rgb(88, 193, 222);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 271, 91))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.donebtn = QtWidgets.QPushButton(self.centralwidget)
        self.donebtn.setGeometry(QtCore.QRect(580, 80, 141, 41))
        self.donebtn.setStyleSheet("QPushButton {\n"
"    box-shadow: 0px 10px 14px -7px #000000;\n"
"    background:linear-gradient(to bottom, #112126 5%, #636363 100%);\n"
"    background-color:#112126;\n"
"    border-radius:8px;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color:#ffffff;\n"
"    font-family:Arial;\n"
"    font-size:20px;\n"
"    font-weight:bold;\n"
"    padding:13px 32px;\n"
"    text-decoration:none;\n"
"    text-shadow:0px 1px 0px #000000;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #636363 5%, #112126 100%);\n"
"    background-color:#636363;\n"
"}\n"
"QPushButton:active {\n"
"    position:relative;\n"
"    top:1px;\n"
"}")
        self.donebtn.setObjectName("donebtn")
        self.donebtn.clicked.connect(self.on_donebtn_clicked)

        self.elvl = QtWidgets.QProgressBar(self.centralwidget)
        self.elvl.setGeometry(QtCore.QRect(330, 180, 311, 16))
        self.elvl.setStyleSheet("color: rgb(55, 255, 41);")
        self.elvl.setMaximum(100)
        self.elvl.setStyleSheet("background-color: blue;")
        self.elvl.setProperty("value", 0)
        self.elvl.setTextVisible(False)
        self.elvl.setOrientation(QtCore.Qt.Horizontal)
        self.elvl.setInvertedAppearance(False)
        self.elvl.setObjectName("elvl")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.einput = QtWidgets.QLineEdit(self.centralwidget)
        self.einput.setGeometry(QtCore.QRect(300, 80, 261, 41))
        self.einput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.einput.setText("")
        self.einput.setObjectName("einput")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.edesc = QtWidgets.QTextEdit(self.centralwidget)
        self.edesc.setGeometry(QtCore.QRect(410, 250, 441, 131))
        self.edesc.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.edesc.setObjectName("edesc")
        self.error = QtWidgets.QTextEdit(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(20, 410, 491, 87))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color:rgb(255, 12, 16);\n"
"border:none;\n"
"background-color: rgb(88, 193, 222);")
        self.error.setObjectName("error")
        self.error.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)  # Make links clickable
        self.error.setHtml("") 
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Input Your Emoji"))
        self.donebtn.setText(_translate("MainWindow", "DONE"))
        self.label_2.setText(_translate("MainWindow", "Emoji stress Level"))
        self.einput.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.einput.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Description of the emoji"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
